services:
  model-svc:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - outputs:/app/outputs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  outputs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$PWD/outputs"